// Generated register defines for heepocrates_ctrl

// Copyright information found in source file:
// Copyright lowRISC contributors.

// Licensing information found in source file:
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef _HEEPOCRATES_CTRL_REG_DEFS_
#define _HEEPOCRATES_CTRL_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define HEEPOCRATES_CTRL_PARAM_REG_WIDTH 32

// Mem0 - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_MEM0_SW_MONITOR_REG_OFFSET 0x0
#define HEEPOCRATES_CTRL_MEM0_SW_MONITOR_MEM0_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_MEM0_SW_MONITOR_MEM0_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_MEM0_SW_MONITOR_MEM0_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_MEM0_SW_MONITOR_MEM0_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_MEM0_SW_MONITOR_MEM0_SW_MONITOR_OFFSET })

// Mem1 - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_MEM1_SW_MONITOR_REG_OFFSET 0x4
#define HEEPOCRATES_CTRL_MEM1_SW_MONITOR_MEM1_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_MEM1_SW_MONITOR_MEM1_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_MEM1_SW_MONITOR_MEM1_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_MEM1_SW_MONITOR_MEM1_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_MEM1_SW_MONITOR_MEM1_SW_MONITOR_OFFSET })

// Mem2 - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_MEM2_SW_MONITOR_REG_OFFSET 0x8
#define HEEPOCRATES_CTRL_MEM2_SW_MONITOR_MEM2_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_MEM2_SW_MONITOR_MEM2_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_MEM2_SW_MONITOR_MEM2_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_MEM2_SW_MONITOR_MEM2_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_MEM2_SW_MONITOR_MEM2_SW_MONITOR_OFFSET })

// Mem3 - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_MEM3_SW_MONITOR_REG_OFFSET 0xc
#define HEEPOCRATES_CTRL_MEM3_SW_MONITOR_MEM3_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_MEM3_SW_MONITOR_MEM3_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_MEM3_SW_MONITOR_MEM3_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_MEM3_SW_MONITOR_MEM3_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_MEM3_SW_MONITOR_MEM3_SW_MONITOR_OFFSET })

// Mem4 - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_MEM4_SW_MONITOR_REG_OFFSET 0x10
#define HEEPOCRATES_CTRL_MEM4_SW_MONITOR_MEM4_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_MEM4_SW_MONITOR_MEM4_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_MEM4_SW_MONITOR_MEM4_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_MEM4_SW_MONITOR_MEM4_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_MEM4_SW_MONITOR_MEM4_SW_MONITOR_OFFSET })

// Mem5 - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_MEM5_SW_MONITOR_REG_OFFSET 0x14
#define HEEPOCRATES_CTRL_MEM5_SW_MONITOR_MEM5_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_MEM5_SW_MONITOR_MEM5_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_MEM5_SW_MONITOR_MEM5_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_MEM5_SW_MONITOR_MEM5_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_MEM5_SW_MONITOR_MEM5_SW_MONITOR_OFFSET })

// Mem6 - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_MEM6_SW_MONITOR_REG_OFFSET 0x18
#define HEEPOCRATES_CTRL_MEM6_SW_MONITOR_MEM6_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_MEM6_SW_MONITOR_MEM6_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_MEM6_SW_MONITOR_MEM6_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_MEM6_SW_MONITOR_MEM6_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_MEM6_SW_MONITOR_MEM6_SW_MONITOR_OFFSET })

// Mem7 - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_MEM7_SW_MONITOR_REG_OFFSET 0x1c
#define HEEPOCRATES_CTRL_MEM7_SW_MONITOR_MEM7_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_MEM7_SW_MONITOR_MEM7_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_MEM7_SW_MONITOR_MEM7_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_MEM7_SW_MONITOR_MEM7_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_MEM7_SW_MONITOR_MEM7_SW_MONITOR_OFFSET })

// CGRA Mem - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_CGRA_MEM_SW_MONITOR_REG_OFFSET 0x20
#define HEEPOCRATES_CTRL_CGRA_MEM_SW_MONITOR_CGRA_MEM_SW_MONITOR_MASK 0xf
#define HEEPOCRATES_CTRL_CGRA_MEM_SW_MONITOR_CGRA_MEM_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_CGRA_MEM_SW_MONITOR_CGRA_MEM_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_CGRA_MEM_SW_MONITOR_CGRA_MEM_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_CGRA_MEM_SW_MONITOR_CGRA_MEM_SW_MONITOR_OFFSET })

// Coubertin Mem - Used to read Schmitt Trigger
#define HEEPOCRATES_CTRL_COUBERTIN_SW_MONITOR_REG_OFFSET 0x24
#define HEEPOCRATES_CTRL_COUBERTIN_SW_MONITOR_COUBERTIN_SW_MONITOR_MASK 0x3
#define HEEPOCRATES_CTRL_COUBERTIN_SW_MONITOR_COUBERTIN_SW_MONITOR_OFFSET 0
#define HEEPOCRATES_CTRL_COUBERTIN_SW_MONITOR_COUBERTIN_SW_MONITOR_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_COUBERTIN_SW_MONITOR_COUBERTIN_SW_MONITOR_MASK, .index = HEEPOCRATES_CTRL_COUBERTIN_SW_MONITOR_COUBERTIN_SW_MONITOR_OFFSET })

// Enable CGRA top wrapper clock gating unit
#define HEEPOCRATES_CTRL_CGRA_ENABLE_REG_OFFSET 0x28
#define HEEPOCRATES_CTRL_CGRA_ENABLE_CGRA_ENABLE_MASK 0x3
#define HEEPOCRATES_CTRL_CGRA_ENABLE_CGRA_ENABLE_OFFSET 0
#define HEEPOCRATES_CTRL_CGRA_ENABLE_CGRA_ENABLE_FIELD \
  ((bitfield_field32_t) { .mask = HEEPOCRATES_CTRL_CGRA_ENABLE_CGRA_ENABLE_MASK, .index = HEEPOCRATES_CTRL_CGRA_ENABLE_CGRA_ENABLE_OFFSET })

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _HEEPOCRATES_CTRL_REG_DEFS_
// End generated register defines for heepocrates_ctrl